# Copyright (c) 2024 John Messenger. All rights reserved.

use OscWave::Point

class LevelEntry
  @level: Level

  @period: Integer

  include Comparable

  @start: Point

  attr_reader level: untyped

  attr_reader period: untyped

  class Level
    LOW: Symbol
    HIGH: Symbol

    @level: Symbol

    def invert: -> Level
  end

  # @param [Point] start the starting Point (level and position)
  # @param [Integer] period the number of periods for which the wave remains at this level
  def initialize: (Point start, Integer period) -> void

  def <=>: (untyped other) -> untyped

  def self.!: (LevelEntry) -> LevelEntry
end
