# Copyright (c) 2024 John Messenger. All rights reserved.

module OscWave
  class Point
    @position: Integer

    @level: LevelEntry::Level

    attr_accessor position: Integer

    attr_accessor level: LevelEntry::Level

    def initialize: (Integer position, LevelEntry::Level level) -> void

    def -: (untyped other) -> untyped
  end
end
